#!/usr/bin/perl

use strict;
use warnings;

if ($#ARGV != 0) {
  die "usage: $0 filename.csv\n";
}

open(INPUT, $ARGV[0]);
while (<INPUT>) {
  chomp;
  if (/^([^,]*),(.*)$/) {
    unless (-d $1) {
      mkdir $1;
    }
    system "wget -c -w5 --directory-prefix=./$1 $2";
  }
}
