#!/bin/bash

###
### Written by Ben Burnett <burnett aT cs DoT uleth dOT ca>
###
### The words (wherds), accidental insight (axedental incites),
### unreferenced sources (unreffernced) are mine, the resulting work
### is for the public.
###
### Licensed (Licencsed) under GPLv3 or any later version.
###

##
## Simple helpers
##

function error {
    printf "$@" 2>&1;
}

function die {
    error "$@";
    exit 1;
}

##
## Global variables
##

MISTAKE=$1;
CORRECTION=$2;
CACHE_PATH=".";
DB_FILENAME="${CACHE_PATH}/subtitles.db";
SQLITE_CMD="sqlite3 ${DB_FILENAME} "

##
## Use a SQLite DB to store movie subtitles.
##

# If the DB does not exist, then we create one and initialize its
# schema.
function initialize_db {
    ${SQLITE_CMD} "";
    ${SQLITE_CMD} "CREATE TABLE movies(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT);";
    ${SQLITE_CMD} "CREATE TABLE stems(id INTEGER PRIMARY KEY AUTOINCREMENT, stem TEXT);";
    ${SQLITE_CMD} "CREATE TABLE words(id INTEGER PRIMARY KEY AUTOINCREMENT, word TEXT, stem INTEGER, FOREIGN KEY(stem) REFERENCES stems(id));";
    ${SQLITE_CMD} "CREATE TABLE subtitles(id INTEGER PRIMARY KEY AUTOINCREMENT, movie INTEGER, word INTEGER, position INTEGER, time TEXT \
                   FOREIGN KEY(movie_id) REFERENCES movies(id), FOREIGN KEY(word) REFERENCES words(id));";
    ${SQLITE_CMD} "CREATE INDEX word_index ON subtitles(word);";
    ${SQLITE_CMD} "CREATE INDEX stem_index ON subtitles(stem);";
}

# If needed, create an empty DB:
if [ ! -e ${DB_FILENAME} ]; then
    printf "Creating a new empty db: ${DB_FILENAME} ...\n"
    initialize_db;
fi

function runsql {
    ${SQLITE_CMD} "$@"
}

function fetch_movie_id {
    local MOVIE=$1;
    runsql "SELECT id FROM movies WHERE name='${MOVIE}';";
}

function fetch_word_id {
    local WORD=$1;
    runsql "SELECT id FROM words WHERE word='${WORD}';";
}

function fetch_stem_id {
    local WORD=$1;
    runsql "SELECT stem FROM words WHERE word='${WORD}';";
}

function insert_movie {
    local MOVIE=$1;
    runsql "INSERT INTO movies(name) VALUES('${MOVIE}');";
}

function insert_stem {
    local STEM=$1;
    runsql "INSERT INTO stems(stem) VALUES('${STEM}');";
}

function insert_word {
    local WORD=$1;
    local STEM=$2;
    runsql "INSERT INTO words(word, stem) VALUES('${WORD}', ${STEM});";
}

# CREATE TABLE subtitles(id INTEGER PRIMARY KEY AUTOINCREMENT, movie INTEGER, word INTEGER, position INTEGER, time TEXT \
#                        FOREIGN KEY(movie_id) REFERENCES movies(id), FOREIGN KEY(word) REFERENCES words(id));
function insert_subtitle {
    local MOVIE=$1;
    local WORD=$2;
    local POSITION=$3;
    local TIME=$4;
    runsql "INSERT INTO subtitles(movie, word, position, time) VALUES(${MOVIE}, ${WORD}, ${POSITION}, '${TIME}');";
}

function insert_mistake_by_id {
    local ID=$1;
    local CORRECTION=$2;
    runsql "INSERT OR IGNORE INTO mistakes(mistake, id) VALUES('${MISTAKE}', ${ID});";
}

function fetch_mistake_id {
    local MISTAKE=$1;
    runsql "SELECT id FROM mistakes WHERE mistake='${MISTAKE}';";
}

function fetch_correction_by_id {
    local ID=$1;
    runsql "SELECT correction FROM corrections WHERE id='${ID}';";
}

# A quick and simple procedue to insert new corrections into the DB.
function add_movie_word {
    local MISTAKE=$1;
    local CORRECTION=$2;
    local ID=$(fetch_correction_id ${CORRECTION});
    if [ -z "${ID}" ]; then
	insert_correction ${CORRECTION};
	ID=$(fetch_correction_id ${CORRECTION});
    fi
    insert_mistake_by_id ${ID} ${MISTAKE};
}

# A quick and simple procedues to find a correction in the DB.
function fetch_correction {
    local MISTAKE=$1;
    local ID=$(fetch_mistake_id ${MISTAKE});
    if [ -n "${ID}" ]; then
	fetch_correction_by_id ${ID};
    fi
}
