#!/usr/bin/perl -w

###
### Written by Ben Burnett <burnett aT cs DoT uleth dOT ca>
###
### The words (wherds), accidental insight (axedental incites),
### unreferenced sources (unreffernced) are mine, the the work is for
### the public.
###
### Licensed (Licencsed) under GPLv3 or any later version.
###

use strict;
use warnings;
use threads;
use Lingua::Stem qw(stem);

# Just one file at a time.
if ($#ARGV != 0) {
  die "usage: $0 filename\n";
}

# We should be receiving one file
my $wordfile = $ARGV[0];

# The words are the fist entry on each line
my @words;
my @remainder;
open (INPUT, "<$wordfile");
while (<INPUT>) {
  chomp;
  if (/^([^,]*),\ +(.*)$/) {
    push(@words,$1);
    push(@remainder,$2);
  }
}

# Generate the stem for each word and calculate the stem's frequency
my @unique;
my %seen = ();
my $stems = stem(@words);
foreach (@$stems) {
  push(@unique, $_) unless $seen{$_}++;
}

# Print the results
my @threads;
push(@threads,threads->new(\&print_words));
push(@threads,threads->new(\&print_stems));
foreach (@threads) {
  $_->join;
}

# Print the the original information, including the stem
sub print_words {
  for my $i (0 .. $#words) {
    printf "$words[$i], @$stems[$i], $remainder[$i]\n";
  }
}

# Print all non-empty stems and their frequency
sub print_stems {
  foreach (@unique) {
    print STDERR "$_, $seen{$_}\n" unless !$_;
  }
}
